apiVersion: v1
kind: Service
metadata:
  name: camunda
  namespace: camunda
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: camunda-platform
